POST http://localhost:8080/localhost:8080/api/led HTTP/1.1
Content-Type: application/json

{
    "number": 2,
    "state": false
}

###
GET http://localhost:8080/api/led

###
GET http://localhost:8080/api/led/ryQy0Kw503CYYRnl

###
PATCH  http://localhost:8080/api/led/ryQy0Kw503CYYRnl HTTP/1.1
content-type: application/json

{
    "state": true
}

###
DELETE http://localhost:8080/api/led/Hpyi2EVRIPbE1EAd